### ISSUE TITLE
🐞 `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }

### ISSUE THREAD

**Issue by cryophyte** [tgotwig/vidmerger#39]
I'm got this when I try to merge the video and audio "> vidmerger --format mp4 C:\Users\Bahaa\Downloads\episodes" :

- ffmpeg -i C:\Users\xenpai\Downloads\episodes\video (540p with 25fps).mp4 -r 0 C:\Users\xenpai\AppData\Local\Temp\np3f70Un\vid (540p with 25fps).mp4 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\helpers\io_helper.rs:52:18

Also I got a failer when I run "choco install ffmpeg # prerequisite" :

Removing extracted archive.
Sleeping for 2 seconds to allow anti-viruses to finish scanning...
Renaming ffmpeg directory to common name (Try 1 / 3)
Successfully renamed directory.
 ShimGen has successfully created a shim for ffmpeg.exe
 ShimGen has successfully created a shim for ffplay.exe
 ShimGen has successfully created a shim for ffprobe.exe
 The install of ffmpeg was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\ffmpeg\tools'
# not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.
prerequisite not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.

**Comment by tgotwig** [comment]
Hello again 🙋 

Have you tried more simple file names?
Have you tried to install ffmpeg as admin?

**Comment by fxaurum** [comment]
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\helpers\io_helper.rs:52:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

I have successfully installed ffmpeg and vidmerger, but I am still encountering errors.

**Comment by tgotwig** [comment]
Should be probably fixed with version 0.4.0 https://github.com/tgotwig/vidmerger/commit/70d61e54da75449521d309c241734b4674a1f08f
